### ISSUE TITLE
Consuming Rest API

### ISSUE THREAD

**Issue by ppusapati** [batazor/microservice-template-ddd#80]
Was trying to implement this template in a new project. Need proper documentation to understand.

1. Have modified this as there was no package with tag 1.21 for jaegertracing/spark-dependencies as mentioned in infrastructure/opentracing.yaml
https://hub.docker.com/r/jaegertracing/spark-dependencies/tags?page=1&ordering=last_updated
2. How to consume rest API from localhost:7070 links provided in postman were not working 
https://batazor.github.io/microservice-template-ddd/docs/microservice-template-ddd.postman_collection.json
3. Have also commented Handler: chi.ServerBaseContext(ctx,r) at line 61 in /internal/api/http/server.go as this is outdated and go-chi has removed this method ServerBaseContext

**Comment by batazor** [comment]
@ppusapati Thank you so much for your help! I fixed the obsolete dependencies and verified that the containers are built right and requests to postman now work correctly.
